export const JOB_ROLES = [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "Desktop App Developer",
    "Web Developer",
    "Software Engineer",
    "Application Developer",
    "Game Developer",
    "AR / VR Developer",
    "Blockchain Developer",
    "AI / ML Engineer",
    "Data Scientist",
    "IoT Developer",
    "Database Administrator (DBA)",
    "Data Engineer",
    "Big Data Developer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Site Reliability Engineer (SRE)",
    "QA Engineer / Tester",
    "Automation Tester",
    "Security Engineer / Ethical Hacker",
    "UI Designer",
    "UX Designer",
    "Tech Lead",
    "Software Architect",
    "Project Manager",
    "Product Manager",
    "Scrum Master",
    "System Administrator",
    "IT Support Engineer",
    "Network Engineer",
    "Solutions Architect",
    "Technical Consultant",
    "Junior Developer",
    "Mid-Level Developer",
    "Senior Developer",
    "Principal Engineer",
    "Android Developer",
    "iOS Developer",
    "Cross-Platform Developer",
    "UI Developer",
    "Embedded Systems Developer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Cyber Security Engineer",
    "Automation Test Engineer",
    "UI/UX Designer",
    "Business Analyst",
    "Engineering Manager",
    "CTO (Chief Technology Officer)",
    "Technical Support Engineer",
    "Freelance Developer",
    "Low-Code / No-Code Developer",
    "Intern"
];
